### ISSUE TITLE
How to integrate Report NG with jenkins?

### ISSUE THREAD

**Issue by aliasgerkw** [testng-team/reportng#11]
Or it will be same as default Test NG report works it will automatically take ReportNG reports as Test Results?

**Comment by krmahadevan** [comment]
You don't need to do anything extra for you to be able to generate ReportNG reports (since its added via Service Providers). You should be able to find the ReportNG reports in the **target/surefire-reports/**

**Comment by aliasgerkw** [comment]
My query was related to Jenkins Integration though. Do I need to add any new plugin there to enable to see this report?

**Comment by krmahadevan** [comment]
@aliasgerkw - There is no plugin etc for this. Whatever mechanism you are using to have Jenkins show the default HTML report that comes baked into TestNG, you would use the same approach to show this report as well.

Not every report needs a Jenkins plugin for it to be rendered. Its true in the case of sophisticated reporting mechanism such as allure because, the html gets generated in runtime. But that's not the case with ReportNG.

**Comment by aliasgerkw** [comment]
Thanks @krmahadevan for the clarification
